### ISSUE TITLE
Consider releasing a new version so this can be used from projects with MSRV 1.70?

### ISSUE THREAD

**Issue by gretchenfrage** [tomtomwombat/fastbloom#9]
I'm exploring the possibility of using this crate in https://github.com/quinn-rs/quinn/pull/1912. Quinn has an MSRV of 1.70. Fastbloom supports an MSRV of 1.70 as of #8 in October, however, that commit has not been published yet, as the last release was in April. Would you consider publishing a new version?

**Comment by tomtomwombat** [comment]
Yeah sure, give me 20 minutes

**Comment by gretchenfrage** [comment]
No rush

**Comment by tomtomwombat** [comment]
It's about time, here ya go https://crates.io/crates/fastbloom/0.8.0
